class ExpansionDefines {
  // From https://github.com/salutesh/DayZ-Expansion-Scripts/wiki/%5BServer-Hosting%5D-List-of-default-icon-names
  static final List<String> availableIconNames = [
    "Airdrop",
    "Animal Skull",
    "Apple",
    "Apple Core",
    "Arrow",
    "Arrows",
    "Axe",
    "Backpack",
    "Bandage",
    "Base",
    "Batteries",
    "Battery Empty",
    "Battery Full",
    "Battery Low",
    "Battery Med",
    "Bear",
    "Berries",
    "Binoculars",
    "Boat",
    "Bolt",
    "Bonfire",
    "Book 1",
    "Book 2",
    "Bottle",
    "Bow",
    "Broken Lighter",
    "Can Of Beans Big",
    "Can Of Beans Small",
    "Car",
    "Car 2",
    "Car Keys",
    "Carrot",
    "Chain Saw",
    "Chicken",
    "Chocolate",
    "Cigarets",
    "Claw",
    "Cloth",
    "Compass",
    "Corn",
    "Cow",
    "Craft",
    "Cross",
    "Crowbar",
    "Deliver",
    "Dinosaur Skull",
    "Discord",
    "Drip",
    "Dry Wood",
    "Ear",
    "Eatable Flowers",
    "Electrical Tape",
    "Ellipse",
    "Empty Can",
    "Error",
    "Exclamationmark",
    "Expansion",
    "Expansion B/W",
    "Eye",
    "Fireplace",
    "Fish",
    "Fishing",
    "Flare",
    "Flare Gun",
    "Flare Gun Ammo",
    "Flashlight",
    "Forums",
    "Fox",
    "Frying Pan",
    "Gas",
    "Gas Mask",
    "GitHub",
    "Golf Club",
    "Goose",
    "Grab",
    "Grenade",
    "Group",
    "Guilded",
    "Guitar",
    "Gun",
    "Gun Bullets",
    "Hammer",
    "Heart",
    "Helicopter",
    "Herbal Medicine",
    "Home Made Grenade",
    "Homepage",
    "Hook",
    "Human Skull",
    "Infected 1",
    "Infected 2",
    "Info",
    "Insect",
    "Kitchen Knife",
    "Kitchen Knife Big",
    "Knife",
    "Ladder",
    "Lantern",
    "Lighter",
    "Machette",
    "Map",
    "Map Marker",
    "Marker",
    "Matches",
    "Medic Box",
    "Menu",
    "Moon",
    "Mushrooms",
    "Nails",
    "Note",
    "Open Hand",
    "Orientation",
    "Paper",
    "Paper Map",
    "Patreon",
    "PayPal",
    "Pen",
    "Persona",
    "Pill",
    "Pills",
    "Pipe Wrench",
    "Powder",
    "Pumpkin",
    "Questionmark",
    "Questionmark 2",
    "Rabbit",
    "Racoon",
    "Radiation",
    "Radio",
    "Radio",
    "Rat",
    "Reddit",
    "Rock 1",
    "Rock 2",
    "Rope",
    "Saw",
    "Scrap Metal",
    "Screwdriver",
    "Shield",
    "Shotgun",
    "Shotgun Bullets",
    "Shovel",
    "Skull 1",
    "Skull 2",
    "Skull 3",
    "Snow",
    "Soda",
    "Square",
    "Star",
    "Steam",
    "Sun",
    "Tent",
    "Tent",
    "Territory",
    "Thermometer",
    "Trader",
    "Twitter",
    "Vehicle Crash",
    "Walkie Talkie",
    "Water 1",
    "Water 2",
    "Water Jug",
    "Wild Pork",
    "Worms",
    "YouTube"
  ];
}